### ISSUE TITLE
Urbit Visor won't Load on Dashboard 

### ISSUE THREAD

**Issue by Duncanswilson** [dcSpark/urbit-dashboard#48]
I have urbit visor properly set up but when I go to the dashboard page I see this: 
<img width="1247" alt="Screen Shot 2021-10-21 at 5 31 40 AM" src="https://user-images.githubusercontent.com/7635452/138277779-77fdd387-4cee-401c-8d42-32815bed2d73.png">
<img width="566" alt="Screen Shot 2021-10-21 at 5 31 25 AM" src="https://user-images.githubusercontent.com/7635452/138277788-1cd5b703-fce6-4877-b7be-320556dd48cb.png">

**Comment by robkorn** [comment]
Feel free to install via the chrome web store to get up and running quickly and address this issue: https://chrome.google.com/webstore/detail/urbit-visor/oadimaacghcacmfipakhadejgalcaepg
